apiVersion: apps/v1
kind: Deployment
metadata:
  name: intainva-external-app
  namespace: fabricclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-external-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-external-app
    spec:
      containers:
        - image: {{image}}
          imagePullPolicy: Always
          name: node-external-app
          ports:
            - containerPort: 3005
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/node-app/uploads
              name: external-app-azurefile
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: external-app-azurefile
          persistentVolumeClaim:
            claimName: external-app-pvc
