apiVersion: v1
kind: Service
metadata:

  name: node-external-service
  namespace: fabricclient
spec:

  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3005
      protocol: TCP
      targetPort: 3005
  selector:
    app: node-external-app
  sessionAffinity: None
  type: ClusterIP
